apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workshop-kubernetes-[seunome]
  namespace: desenvolvimento
spec:
  selector:
    matchLabels:
      app: workshop-kubernetes-[seunome]
  replicas: 1
  template:
    metadata:
      labels:
        app: workshop-kubernetes-[seunome]
    spec:
      containers:
        - name: workshop-kubernetes-[seunome]
          image: daniloar/workshop-kubernetes
          imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: workshop-kubernetes-[seunome]
  namespace: desenvolvimento
  labels:
    app: workshop-kubernetes-[seunome]
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: workshop-kubernetes-[seunome]
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: workshop-kubernetes-[seunome]
  namespace: desenvolvimento
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cluster-workshop.westus2.cloudapp.azure.com
      http:
        paths:
          - path: /workshop-kubernetes/[seunome]
            backend:
              serviceName: workshop-kubernetes-[seunome]
              servicePort: 80
